#name: hospital_nestor_kirchner

services:
  ldap:
    image: dcm4che/slapd-dcm4chee:2.6.5-31.2
    env_file:
      - ldap.env
    logging:
      driver: json-file
      options:
        max-size: "10m"
    networks:
      - arc-net
    ports:
      - "389:389"
      - "636:636"
    restart: unless-stopped
    volumes:
      - ${OPENLDAP_DATA_PATH:-/opt/dcm4chee-arc/openldap-data}:/var/lib/openldap/openldap-data
      - ${SLAPD_PATH:-/opt/dcm4chee-arc/slapd.d}:/etc/openldap/slapd.d
  mariadb:
    image: mariadb
    env_file:
      - mariadb.env
    logging:
      driver: json-file
      options:
        max-size: "10m"
    networks:
      - arc-net
    ports:
      - "3306:3306"
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ${MARIADB_PATH:-/opt/dcm4chee-arc/mysql}:/var/lib/mysql
  keycloak:
    image: dcm4che/keycloak:24.0.1
    env_file:
      - keycloak.env
    logging:
      driver: json-file
      options:
        max-size: "10m"
    networks:
      - arc-net
    ports:
      - "8843:8843"
    environment:
      KEYCLOAK_WAIT_FOR: ldap:389 mariadb:3306
    restart: unless-stopped
    depends_on:
      - ldap
      - mariadb
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ${KEYCLOAK_PATH:-/opt/dcm4chee-arc/keycloak}:/opt/keycloak/data
  db:
    image: dcm4che/postgres-dcm4chee:15.4-31
    env_file:
      - ./db.env
    logging:
      driver: json-file
      options:
        max-size: "10m"
    networks:
      - arc-net
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ${POSTGRES_PATH:-/opt/dcm4chee-arc/db}:/var/lib/postgresql/data
  arc:
    image: dcm4che/dcm4chee-arc-psql:5.31.2-secure-ui
    env_file:
      - arc.env
    networks:
      - arc-net
    ports:
      - "8080:8080"
      - "8443:8443"
      - "9990:9990"
      - "9993:9993"
      - "11112:11112"
      - "2762:2762"
      - "2575:2575"
      - "12575:12575"
    environment:
      WILDFLY_WAIT_FOR: ldap:389 db:5432 keycloak:8843
    restart: unless-stopped
    depends_on:
      - ldap
      - keycloak
      - db
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ${WILDFLY_PATH:-/opt/dcm4chee-arc/wildfly}:/opt/wildfly/standalone
      - ${PACS_STORAGE_PATH:-/opt/dcm4chee-arc/storage}:/storage

networks:
  arc-net:
    name: arc-net
    ipam:
          driver: default
          config:
            - subnet: 192.168.255.0/24
              ip_range: 192.168.255.0/24
              gateway: 192.168.255.254
